--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 9.3 Revision 2 from HDL Works B.V.
--
-- Ease library  : Work
-- HDL library   : Work
-- Host name     : NB21-B0I-YME
-- User name     : yves.meyer
-- Time stamp    : Tue Jan  2 18:25:44 2024
--
-- Designed by   : M.Meyer/Y.Meyer
-- Company       : Haute Ecole Arc
-- Project info  : nanoProcesseur
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity Work.Operandes_Multiplexer
-- Last modified : Tue Jul  8 11:11:56 2014
--------------------------------------------------------------------------------

library ieee;
use Work.nanoProcesseur_package.all;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

entity Operandes_Multiplexer is
  port (
    sel_i   : in     std_logic_vector(2 downto 0);
    Accu_i  : in     std_logic_vector(7 downto 0);
    const_i : in     std_logic_vector(7 downto 0);
    data_i  : in     std_logic_vector(7 downto 0);
    oper1_o : out    std_logic_vector(7 downto 0);
    oper2_o : out    std_logic_vector(7 downto 0));
end entity Operandes_Multiplexer;

--------------------------------------------------------------------------------
-- Object        : Architecture Work.Operandes_Multiplexer.Behavioral
-- Last modified : Tue Jul  8 11:11:56 2014
--------------------------------------------------------------------------------

architecture Behavioral of Operandes_Multiplexer is


begin

with sel_i select
  oper1_o <= Accu_i  when MUX_ACCU,
             const_i when MUX_CONST,
             data_i  when MUX_DATA,
             Accu_i  when others;
               
with sel_i select
  oper2_o <= const_i when MUX_ACCU_CONST,
             data_i  when MUX_ACCU_DATA,
             Accu_i  when others;
             
	  
end architecture Behavioral ; -- of Operandes_Multiplexer
