set_property PACKAGE_PIN J19 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property PACKAGE_PIN T18 [get_ports reset_i]
set_property IOSTANDARD LVCMOS33 [get_ports reset_i]
set_property PACKAGE_PIN G20 [get_ports {port_a_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_i[0]}]
set_property PACKAGE_PIN H22 [get_ports {port_a_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_i[1]}]
set_property PACKAGE_PIN J21 [get_ports {port_a_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_i[2]}]
set_property PACKAGE_PIN J22 [get_ports {port_a_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_i[3]}]
set_property PACKAGE_PIN K21 [get_ports {port_a_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_i[4]}]
set_property PACKAGE_PIN K22 [get_ports {port_a_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_i[5]}]
set_property PACKAGE_PIN M21 [get_ports {port_a_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_i[6]}]
set_property PACKAGE_PIN M22 [get_ports {port_a_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_i[7]}]
set_property PACKAGE_PIN N22 [get_ports {port_b_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b_i[0]}]
set_property PACKAGE_PIN G17 [get_ports {port_b_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b_i[1]}]
set_property PACKAGE_PIN G18 [get_ports {port_b_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b_i[2]}]
set_property PACKAGE_PIN H18 [get_ports {port_b_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b_i[3]}]
set_property PACKAGE_PIN H20 [get_ports {port_b_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b_i[4]}]
set_property PACKAGE_PIN J17 [get_ports {port_b_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b_i[5]}]
set_property PACKAGE_PIN J20 [get_ports {port_b_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b_i[6]}]
set_property PACKAGE_PIN H15 [get_ports {port_b_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b_i[7]}]
set_property PACKAGE_PIN G13 [get_ports {port_a_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_o[0]}]
set_property PACKAGE_PIN H14 [get_ports {port_a_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_o[1]}]
set_property PACKAGE_PIN G15 [get_ports {port_a_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_o[2]}]
set_property PACKAGE_PIN G16 [get_ports {port_a_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_o[3]}]
set_property PACKAGE_PIN H17 [get_ports {port_a_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_o[4]}]
set_property PACKAGE_PIN J16 [get_ports {port_a_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_o[5]}]
set_property PACKAGE_PIN K17 [get_ports {port_a_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_o[6]}]
set_property PACKAGE_PIN L20 [get_ports {port_a_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_a_o[7]}]

set_property PACKAGE_PIN V22   [get_ports port_b_o[0]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[0]]
set_property PACKAGE_PIN W22   [get_ports port_b_o[1]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[1]]
set_property PACKAGE_PIN W21   [get_ports port_b_o[2]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[2]]
set_property PACKAGE_PIN Y22   [get_ports port_b_o[3]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[3]]
set_property PACKAGE_PIN Y21   [get_ports port_b_o[4]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[4]]
set_property PACKAGE_PIN AB22  [get_ports port_b_o[5]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[5]]
set_property PACKAGE_PIN AA21  [get_ports port_b_o[6]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[6]]
set_property PACKAGE_PIN AB20  [get_ports port_b_o[7]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[7]]

set_property PACKAGE_PIN A18   [get_ports port_c_o[0]]; set_property IOSTANDARD LVCMOS33 [get_ports port_c_o[0]]
set_property PACKAGE_PIN B20   [get_ports port_c_o[1]]; set_property IOSTANDARD LVCMOS33 [get_ports port_c_o[1]]
set_property PACKAGE_PIN A20   [get_ports port_c_o[2]]; set_property IOSTANDARD LVCMOS33 [get_ports port_c_o[2]]
set_property PACKAGE_PIN B21   [get_ports port_c_o[3]]; set_property IOSTANDARD LVCMOS33 [get_ports port_c_o[3]]
set_property PACKAGE_PIN B16   [get_ports port_c_o[4]]; set_property IOSTANDARD LVCMOS33 [get_ports port_c_o[4]]
set_property PACKAGE_PIN B18   [get_ports port_c_o[5]]; set_property IOSTANDARD LVCMOS33 [get_ports port_c_o[5]]
set_property PACKAGE_PIN A19   [get_ports port_c_o[6]]; set_property IOSTANDARD LVCMOS33 [get_ports port_c_o[6]]
set_property PACKAGE_PIN A21   [get_ports port_c_o[7]]; set_property IOSTANDARD LVCMOS33 [get_ports port_c_o[7]]


create_clock -period 10.000 -name clk_i -waveform {0.000 5.000}
