--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 9.3 Revision 2 from HDL Works B.V.
--
-- Ease library  : Work
-- HDL library   : Work
-- Host name     : NB21-B0I-YME
-- User name     : yves.meyer
-- Time stamp    : Tue Jan  2 18:25:44 2024
--
-- Designed by   : M.Meyer/Y.Meyer
-- Company       : Haute Ecole Arc
-- Project info  : nanoProcesseur
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity Work.RAM
-- Last modified : Tue Aug 16 09:30:11 2016
--------------------------------------------------------------------------------

library ieee;
use Work.nanoProcesseur_package.all;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

entity RAM is
  port (
    clk_i  : in     std_logic;
    cs_i   : in     std_logic;
    wr_i   : in     std_logic;
    addr_i : in     std_logic_vector(7  downto 0);
    data_i : in     std_logic_vector(7  downto 0);
    data_o : out    std_logic_vector(7  downto 0));
end entity RAM;

--------------------------------------------------------------------------------
-- Object        : Architecture Work.RAM.Behavioral
-- Last modified : Tue Aug 16 09:30:11 2016
--------------------------------------------------------------------------------

architecture Behavioral of RAM is

  type     blocRAM_type is array(0 to 31) of std_logic_vector(7 DOWNTO 0); 
  signal   blocRAM : blocRAM_type;
  
  signal   addr_reg : std_logic_vector(4 DOWNTO 0);

begin

process(clk_i)
begin
  if rising_edge(clk_i) then
    if cs_i = '1' and wr_i = '1' then
      blocRAM(TO_INTEGER(UNSIGNED(addr_i(4 DOWNTO 0)))) <= data_i;
    end if;
    
    addr_reg <= addr_i(4 DOWNTO 0);
    
  end if;
end process;

data_o <= blocRAM(TO_INTEGER(UNSIGNED(addr_i(4 DOWNTO 0))));

end architecture Behavioral ; -- of RAM
