--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 9.3 Revision 2 from HDL Works B.V.
--
-- Ease library  : Work
-- HDL library   : Work
-- Host name     : NB21-B0I-YME
-- User name     : yves.meyer
-- Time stamp    : Tue Jan  2 18:25:44 2024
--
-- Designed by   : M.Meyer/Y.Meyer
-- Company       : Haute Ecole Arc
-- Project info  : nanoProcesseur
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity Work.ROM
-- Last modified : Tue Jan  2 10:51:32 2024
--------------------------------------------------------------------------------

library ieee;
use Work.nanoProcesseur_package.all;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

entity ROM is
  port (
    pc_i : in     std_logic_vector(7 downto 0);
    ir_o : out    std_logic_vector(13 downto 0));
end entity ROM;

--------------------------------------------------------------------------------
-- Object        : Architecture Work.ROM.Behavioral
-- Last modified : Tue Jan  2 10:51:32 2024
--------------------------------------------------------------------------------

architecture Behavioral of ROM is


begin


with pc_i select
    ir_o <=
         -- X"10" load dilswitch 1
         -- X"10" store bargraph 1
         -- X"11" load dilswitch 2
         -- X"11" store 7seg 1
         -- X"E0" RAM
         LOADaddr & X"10" when X"00", -- load dilswitch 1
         STOREaddr & X"E0" when x"01", -- store in ram
         
         LOADaddr & X"11" when X"02", --load dilswitch 2
         BZ0 & x"06" when X"03", -- saut si non égal à 0
         -- if
         LOADaddr & X"E0" when X"04", -- charge la valeur depuis la ram
         STOREaddr & X"10" when x"05", -- affiche la valeur sur le bargraph 1
         
         -- else
         XORaddr & X"E0" when X"06", -- Xor des deux valeurs
         STOREaddr & X"10" when x"07", -- affiche la valeur sur le bargraph 1
         LOADconst & "0011110" when x"08", -- charge la valeur de c
         STOREaddr & X"11" when x"09", -- affiche c sur l'affichage 7seg
         -- end if
         BRA & X"00" when others; -- Boucle à l'adresse X"00" 
          
end architecture Behavioral ; -- of ROM
