--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 9.3 Revision 2 from HDL Works B.V.
--
-- Ease library  : Work
-- HDL library   : Work
-- Host name     : NB21-B0I-YME
-- User name     : yves.meyer
-- Time stamp    : Tue Jan  2 18:25:44 2024
--
-- Designed by   : M.Meyer/Y.Meyer
-- Company       : Haute Ecole Arc
-- Project info  : nanoProcesseur
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity Work.Operandes_Register
-- Last modified : Tue Jul  8 11:11:56 2014
--------------------------------------------------------------------------------

library ieee;
use Work.nanoProcesseur_package.all;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

entity Operandes_Register is
  port (
    clk_i       : in     std_logic;
    oper1_i     : in     std_logic_vector(7 downto 0);
    oper2_i     : in     std_logic_vector(7 downto 0);
    oper_load_i : in     std_logic;
    operande1_o : out    std_logic_vector(7 downto 0);
    operande2_o : out    std_logic_vector(7 downto 0);
    reset_i     : in     std_logic);
end entity Operandes_Register;

--------------------------------------------------------------------------------
-- Object        : Architecture Work.Operandes_Register.behavioral
-- Last modified : Tue Jul  8 11:11:56 2014
--------------------------------------------------------------------------------


architecture behavioral of Operandes_Register is

begin

-- Registres pour les opérandes

p_oper:process(clk_i,reset_i)
begin
  if reset_i = '0' then
    operande1_o <= (others => '0');
    operande2_o <= (others => '0');
  elsif rising_edge(clk_i) then
    if oper_load_i = '1' then
      operande1_o <= oper1_i; 
      operande2_o <= oper2_i;
    end if;
  end if;
end process;

end architecture behavioral ; -- of Operandes_Register

